table DimCustomer
	lineageTag: 0f7afd25-ec57-4d5a-90ab-907e07a1b786

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 2cc2cf2e-0542-4896-ae49-6565301ec9b8
		summarizeBy: count
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column GeographyKey
		dataType: int64
		formatString: 0
		lineageTag: 552ecb54-fda2-48e5-abf8-ab3a18ffc947
		summarizeBy: count
		sourceColumn: GeographyKey

		annotation SummarizationSetBy = Automatic

	column CustomerAlternateKey
		dataType: string
		lineageTag: ccbb9960-71f0-4d31-99c8-e84f6d96d646
		summarizeBy: none
		sourceColumn: CustomerAlternateKey

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: f0ba3e16-331a-4e51-9f52-9598e2d602e8
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 901baae3-bdfa-4021-b253-c847a9c149b0
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column MiddleName
		dataType: string
		lineageTag: e47cd159-b38a-4e1d-9665-1e07d694bc93
		summarizeBy: none
		sourceColumn: MiddleName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: bf6f217f-0640-4e5b-beab-46cef99303d3
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column NameStyle
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0a774a85-f11b-41ad-bc57-2ac553e17cbf
		summarizeBy: none
		sourceColumn: NameStyle

		annotation SummarizationSetBy = Automatic

	column BirthDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: e5148351-9679-4e35-9a09-1f98357405ae
		summarizeBy: none
		sourceColumn: BirthDate

		variation Variation
			isDefault
			relationship: 73df0c13-87ab-4e08-8c8e-c55c28b4c24d
			defaultHierarchy: LocalDateTable_e38c1fc4-90b5-4f84-bb3d-2a665fec5de7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MaritalStatus
		dataType: string
		lineageTag: ad717d0d-30f5-4a22-b70d-bcbe4f93c47f
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column Suffix
		dataType: string
		lineageTag: 61ea1a6b-37b5-418e-a1dc-3d9e5fa194d5
		summarizeBy: none
		sourceColumn: Suffix

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: af397f5c-5f0d-4061-9887-76a62d7f23f7
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column EmailAddress
		dataType: string
		lineageTag: 2357e9e7-0e8d-4c8a-8937-8ead8e5ae991
		summarizeBy: none
		sourceColumn: EmailAddress

		annotation SummarizationSetBy = Automatic

	column YearlyIncome
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 2c2de252-cd55-459c-963c-911777deec10
		summarizeBy: sum
		sourceColumn: YearlyIncome

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column TotalChildren
		dataType: int64
		formatString: 0
		lineageTag: 243cd62c-c6f9-46f6-ae3a-607f890243ff
		summarizeBy: sum
		sourceColumn: TotalChildren

		annotation SummarizationSetBy = Automatic

	column NumberChildrenAtHome
		dataType: int64
		formatString: 0
		lineageTag: 0b956f18-e9f3-4042-a817-51f8958728b5
		summarizeBy: sum
		sourceColumn: NumberChildrenAtHome

		annotation SummarizationSetBy = Automatic

	column EnglishEducation
		dataType: string
		lineageTag: 16035d59-fbbb-42e0-8d73-1058c30b4536
		summarizeBy: none
		sourceColumn: EnglishEducation

		annotation SummarizationSetBy = Automatic

	column SpanishEducation
		dataType: string
		lineageTag: ccea0925-6ae2-4b5c-9894-a090d8483ef1
		summarizeBy: none
		sourceColumn: SpanishEducation

		annotation SummarizationSetBy = Automatic

	column FrenchEducation
		dataType: string
		lineageTag: 99958653-3413-4a68-91ce-de39c64f6ef9
		summarizeBy: none
		sourceColumn: FrenchEducation

		annotation SummarizationSetBy = Automatic

	column EnglishOccupation
		dataType: string
		lineageTag: 1392f0a0-761a-4704-b16c-eb49df722b49
		summarizeBy: none
		sourceColumn: EnglishOccupation

		annotation SummarizationSetBy = Automatic

	column SpanishOccupation
		dataType: string
		lineageTag: 5ffd84e0-d2c8-4a2f-bde8-bf20cf5fc3df
		summarizeBy: none
		sourceColumn: SpanishOccupation

		annotation SummarizationSetBy = Automatic

	column FrenchOccupation
		dataType: string
		lineageTag: a0ae5262-3cff-4417-832d-c3e7c84a0b31
		summarizeBy: none
		sourceColumn: FrenchOccupation

		annotation SummarizationSetBy = Automatic

	column HouseOwnerFlag
		dataType: string
		lineageTag: fe167357-1477-43d6-9de0-07945b933754
		summarizeBy: none
		sourceColumn: HouseOwnerFlag

		annotation SummarizationSetBy = Automatic

	column NumberCarsOwned
		dataType: int64
		formatString: 0
		lineageTag: 63ab505b-eff0-4f46-b6fc-0d3ad1a87447
		summarizeBy: sum
		sourceColumn: NumberCarsOwned

		annotation SummarizationSetBy = Automatic

	column AddressLine1
		dataType: string
		lineageTag: 277b9579-f079-4e76-b270-fe3d9359ff5a
		summarizeBy: none
		sourceColumn: AddressLine1

		annotation SummarizationSetBy = Automatic

	column AddressLine2
		dataType: string
		lineageTag: ae0b4484-c4de-4fba-bbf9-5932d7e90fc5
		summarizeBy: none
		sourceColumn: AddressLine2

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: 5237eda2-0eb9-4064-b589-aa156f3a1c14
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column DateFirstPurchase
		dataType: dateTime
		formatString: Long Date
		lineageTag: 40aa37a7-028e-4247-820d-d125d34ed6c0
		summarizeBy: none
		sourceColumn: DateFirstPurchase

		variation Variation
			isDefault
			relationship: 29ce8d2a-c22b-49b4-9a21-d8cf184cfe65
			defaultHierarchy: LocalDateTable_672c3860-6c3a-4f74-8932-5609d92a0e74.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CommuteDistance
		dataType: string
		lineageTag: 82127176-ee77-4d24-9693-06a81a816631
		summarizeBy: none
		sourceColumn: CommuteDistance

		annotation SummarizationSetBy = Automatic

	partition DimCustomer = m
		mode: import
		queryGroup: 'Dim Customers'
		source =
				let
				    Source = Sql.Database(".", "AdventureWorksDW2022"),
				    dbo_DimCustomer = Source{[Schema="dbo",Item="DimCustomer"]}[Data],
				    #"Removed Duplicates key Columns" = Table.RemoveColumns(dbo_DimCustomer,{"DimGeography", "FactInternetSales", "FactSurveyResponse"})
				in
				    #"Removed Duplicates key Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

