table DimReseller
	lineageTag: 3c217220-6a28-4031-bde8-839e295b3985

	column ResellerKey
		dataType: int64
		formatString: 0
		lineageTag: 80b41719-7141-4067-a3af-821f4ebbea83
		summarizeBy: count
		sourceColumn: ResellerKey

		annotation SummarizationSetBy = Automatic

	column GeographyKey
		dataType: int64
		formatString: 0
		lineageTag: b0051f5e-b48b-4e40-ac89-7c1fb7e12d88
		summarizeBy: count
		sourceColumn: GeographyKey

		annotation SummarizationSetBy = Automatic

	column ResellerAlternateKey
		dataType: string
		lineageTag: f0118205-5515-4525-8ef0-158e84d4e9c1
		summarizeBy: none
		sourceColumn: ResellerAlternateKey

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: a7d8d79b-32be-4bb4-b5fb-39d75446acd6
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column BusinessType
		dataType: string
		lineageTag: 4b4c566c-5232-4e6a-991f-5f1fec8a99db
		summarizeBy: none
		sourceColumn: BusinessType

		annotation SummarizationSetBy = Automatic

	column ResellerName
		dataType: string
		lineageTag: 112bff17-d8a6-4044-92e1-06c39fd3a2bc
		summarizeBy: none
		sourceColumn: ResellerName

		annotation SummarizationSetBy = Automatic

	column NumberEmployees
		dataType: int64
		formatString: 0
		lineageTag: bb8ba9c5-e986-448e-949e-ec49d2c89f8d
		summarizeBy: sum
		sourceColumn: NumberEmployees

		annotation SummarizationSetBy = Automatic

	column OrderFrequency
		dataType: string
		lineageTag: f24c688e-1704-44e5-9a01-17846f0a2f92
		summarizeBy: none
		sourceColumn: OrderFrequency

		annotation SummarizationSetBy = Automatic

	column OrderMonth
		dataType: int64
		formatString: 0
		lineageTag: a5ff70db-5394-407f-88aa-3fbd6eae90a4
		summarizeBy: sum
		sourceColumn: OrderMonth

		annotation SummarizationSetBy = Automatic

	column FirstOrderYear
		dataType: int64
		formatString: 0
		lineageTag: f4c2bb66-ffdf-4207-b20d-45eaf92692a3
		summarizeBy: sum
		sourceColumn: FirstOrderYear

		annotation SummarizationSetBy = Automatic

	column LastOrderYear
		dataType: int64
		formatString: 0
		lineageTag: 48b985b5-c530-4607-9fb0-1f9f1640fc77
		summarizeBy: sum
		sourceColumn: LastOrderYear

		annotation SummarizationSetBy = Automatic

	column ProductLine
		dataType: string
		lineageTag: 05355f7d-81df-4239-99f0-049ca73c29b0
		summarizeBy: none
		sourceColumn: ProductLine

		annotation SummarizationSetBy = Automatic

	column AddressLine1
		dataType: string
		lineageTag: ece730d6-0733-4072-9557-08bc55f8519b
		summarizeBy: none
		sourceColumn: AddressLine1

		annotation SummarizationSetBy = Automatic

	column AddressLine2
		dataType: string
		lineageTag: d869ceb1-d034-40bc-a0df-b1f41309d997
		summarizeBy: none
		sourceColumn: AddressLine2

		annotation SummarizationSetBy = Automatic

	column AnnualSales
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: e8b3830b-0d63-452d-9802-ccf3b52e3fb5
		summarizeBy: sum
		sourceColumn: AnnualSales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column BankName
		dataType: string
		lineageTag: ea3d473a-f536-4d73-b510-1d39190b6441
		summarizeBy: none
		sourceColumn: BankName

		annotation SummarizationSetBy = Automatic

	column MinPaymentType
		dataType: int64
		formatString: 0
		lineageTag: 6582feb3-2258-4943-ab6b-57d7094d7f6c
		summarizeBy: sum
		sourceColumn: MinPaymentType

		annotation SummarizationSetBy = Automatic

	column MinPaymentAmount
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: e0381774-87b9-4c87-90a6-c723a11fade6
		summarizeBy: sum
		sourceColumn: MinPaymentAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column AnnualRevenue
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: d96dee40-c448-4b76-bf06-d706c9d44242
		summarizeBy: sum
		sourceColumn: AnnualRevenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column YearOpened
		dataType: int64
		formatString: 0
		lineageTag: 2ada50b4-5602-454d-aa6e-8eb88f2100bf
		summarizeBy: sum
		sourceColumn: YearOpened

		annotation SummarizationSetBy = Automatic

	partition DimReseller = m
		mode: import
		queryGroup: 'Dim Customers'
		source =
				let
				    Source = Sql.Database(".", "AdventureWorksDW2022"),
				    dbo_DimReseller = Source{[Schema="dbo",Item="DimReseller"]}[Data],
				    #"Removed Duplicates key Columns" = Table.RemoveColumns(dbo_DimReseller,{"DimGeography", "FactResellerSales"})
				in
				    #"Removed Duplicates key Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

