table DimSalesTerritory
	lineageTag: 154e2d17-6e29-4a01-b321-87f1ddfb8bbc

	column SalesTerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: 2864389f-e3b0-44a8-870c-c8044ac25d89
		summarizeBy: count
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryAlternateKey
		dataType: int64
		formatString: 0
		lineageTag: b5dc7b8f-ccbf-4653-b423-787cb5899b53
		summarizeBy: count
		sourceColumn: SalesTerritoryAlternateKey

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryRegion
		dataType: string
		lineageTag: c9a673a9-cc5f-48b9-878d-cf4db0b9d4ea
		summarizeBy: none
		sourceColumn: SalesTerritoryRegion

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryCountry
		dataType: string
		lineageTag: 6c374d19-924f-4828-bf05-d16265a5e24d
		summarizeBy: none
		sourceColumn: SalesTerritoryCountry

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryGroup
		dataType: string
		lineageTag: 8999f240-7d77-40dd-a58a-f585ab5838db
		summarizeBy: none
		sourceColumn: SalesTerritoryGroup

		annotation SummarizationSetBy = Automatic

	partition DimSalesTerritory = m
		mode: import
		queryGroup: 'Dim Geography'
		source =
				let
				    Source = Sql.Database(".", "AdventureWorksDW2022"),
				    dbo_DimSalesTerritory = Source{[Schema="dbo",Item="DimSalesTerritory"]}[Data],
				    #"Removed Duplicates key Columns" = Table.RemoveColumns(dbo_DimSalesTerritory,{"DimEmployee", "DimGeography", "FactInternetSales", "FactResellerSales"})
				in
				    #"Removed Duplicates key Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

