table FactInternetSales
	lineageTag: 7e587fea-3587-4c3a-a57b-0bb779ae031c

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 9213f2aa-a9b7-4e2f-b4ad-ec66d0c4ce03
		summarizeBy: count
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		formatString: 0
		lineageTag: c164931b-b3db-4e14-b7cc-a549960d6924
		summarizeBy: count
		sourceColumn: OrderDateKey

		annotation SummarizationSetBy = Automatic

	column DueDateKey
		dataType: int64
		formatString: 0
		lineageTag: 8afce6c8-f089-4208-8967-cd80cb3e7312
		summarizeBy: count
		sourceColumn: DueDateKey

		annotation SummarizationSetBy = Automatic

	column ShipDateKey
		dataType: int64
		formatString: 0
		lineageTag: 9a0dc045-66e2-48fa-970d-857406b6d807
		summarizeBy: count
		sourceColumn: ShipDateKey

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: e124e789-08ab-4cc8-87a1-f56813e3a23d
		summarizeBy: count
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column PromotionKey
		dataType: int64
		formatString: 0
		lineageTag: bb5b11f3-2408-4863-9e93-bac84305b9d7
		summarizeBy: count
		sourceColumn: PromotionKey

		annotation SummarizationSetBy = Automatic

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: 050093da-e89b-4d0f-900c-7bb0b6e183ac
		summarizeBy: count
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: eeffb0ca-d204-480b-854e-fafad6edac08
		summarizeBy: count
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

	column SalesOrderNumber
		dataType: string
		lineageTag: 3dc2b667-c2e0-4568-b368-4a2a58eed14c
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column SalesOrderLineNumber
		dataType: int64
		formatString: 0
		lineageTag: de315a96-b2cd-4b72-8b2d-dcee11edda29
		summarizeBy: sum
		sourceColumn: SalesOrderLineNumber

		annotation SummarizationSetBy = Automatic

	column RevisionNumber
		dataType: int64
		formatString: 0
		lineageTag: 77d257d9-530b-4c82-8018-7e5894e08dcb
		summarizeBy: sum
		sourceColumn: RevisionNumber

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		lineageTag: aac25c1f-0149-43e8-912f-c5d5101e8c08
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: fcdf3861-14de-486e-bba6-388e7988c6dd
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column ExtendedAmount
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 35d7fd7c-6cf9-4a62-8fe5-7d7aafab6de7
		summarizeBy: sum
		sourceColumn: ExtendedAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column UnitPriceDiscountPct
		dataType: double
		lineageTag: 1c80001f-2a39-4720-8cc2-2e097e610fd0
		summarizeBy: sum
		sourceColumn: UnitPriceDiscountPct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DiscountAmount
		dataType: double
		lineageTag: efe41048-ed15-4b0f-94d7-c4836be50909
		summarizeBy: sum
		sourceColumn: DiscountAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductStandardCost
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 850ffcbe-aa6c-4d1d-a6af-50f109d2e928
		summarizeBy: sum
		sourceColumn: ProductStandardCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column TotalProductCost
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: c8652ac7-d0fe-41d1-b425-e7fe28d56aa4
		summarizeBy: sum
		sourceColumn: TotalProductCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column SalesAmount
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 77f89ca7-30ef-42d6-9d55-35b0f6cf510a
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column TaxAmt
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 1db1b70b-6713-42c4-8a33-463c5f9cbb7c
		summarizeBy: sum
		sourceColumn: TaxAmt

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Freight
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 17f7c938-f875-494d-8d58-64e02e295339
		summarizeBy: sum
		sourceColumn: Freight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column CarrierTrackingNumber
		dataType: string
		lineageTag: caec2ac0-8445-48f1-82e4-4721ce121e2f
		summarizeBy: none
		sourceColumn: CarrierTrackingNumber

		annotation SummarizationSetBy = Automatic

	column CustomerPONumber
		dataType: string
		lineageTag: fe241b86-0c9e-4d8e-8c4e-ea0e5fcdfb52
		summarizeBy: none
		sourceColumn: CustomerPONumber

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: General Date
		lineageTag: bfc5a9cb-5d93-4ec9-8c0f-e6dfea08d560
		summarizeBy: none
		sourceColumn: OrderDate

		variation Variation
			isDefault
			relationship: b054eb8b-1ac7-440e-8e2e-fcdbc2242f18
			defaultHierarchy: LocalDateTable_77132cea-85e1-4d27-be4a-86d74c42a0f0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column DueDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 5b514ad0-f68e-4fba-809b-1201a5c3af80
		summarizeBy: none
		sourceColumn: DueDate

		variation Variation
			isDefault
			relationship: 8e370054-9b8f-4927-855c-bd72d58c2d26
			defaultHierarchy: LocalDateTable_784c90f5-e715-4654-a198-d86b28242a72.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column ShipDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 583b22a3-d254-43b1-a6d4-94d391d48790
		summarizeBy: none
		sourceColumn: ShipDate

		variation Variation
			isDefault
			relationship: 29366f69-e572-4622-82e6-47227ba19086
			defaultHierarchy: LocalDateTable_727d9f21-2536-4ede-b196-8cac6b08a509.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition FactInternetSales = m
		mode: import
		queryGroup: 'Fact Tables'
		source =
				let
				    Source = Sql.Database(".", "AdventureWorksDW2022"),
				    dbo_FactInternetSales = Source{[Schema="dbo",Item="FactInternetSales"]}[Data],
				    #"Removed Duplicates key Columns" = Table.SelectColumns(dbo_FactInternetSales,{"ProductKey", "OrderDateKey", "DueDateKey", "ShipDateKey", "CustomerKey", "PromotionKey", "CurrencyKey", "SalesTerritoryKey", "SalesOrderNumber", "SalesOrderLineNumber", "RevisionNumber", "OrderQuantity", "UnitPrice", "ExtendedAmount", "UnitPriceDiscountPct", "DiscountAmount", "ProductStandardCost", "TotalProductCost", "SalesAmount", "TaxAmt", "Freight", "CarrierTrackingNumber", "CustomerPONumber", "OrderDate", "DueDate", "ShipDate"})
				in
				    #"Removed Duplicates key Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

