table DimCurrency
	lineageTag: efee14e1-610a-4ec9-9cde-af02465c25f4

	column CurrencyKey
		dataType: int64
		formatString: 0
		lineageTag: a4d34fc7-040f-4de5-b4f5-b3acccf4873d
		summarizeBy: none
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

	column CurrencyAlternateKey
		dataType: string
		lineageTag: 68346611-1de8-4847-bf8f-97904554d0f9
		summarizeBy: none
		sourceColumn: CurrencyAlternateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CurrencyName
		dataType: string
		lineageTag: fd63f450-b4c7-474a-9046-82f0dd42d86c
		summarizeBy: none
		sourceColumn: CurrencyName

		annotation SummarizationSetBy = Automatic

	partition DimCurrency = m
		mode: import
		queryGroup: 'Dim Currency'
		source =
				let
				    Source = Sql.Database(".", "AdventureWorksDW2022"),
				    dbo_DimCurrency = Source{[Schema="dbo",Item="DimCurrency"]}[Data],
				    #"Removed Duplicates key Columns" = Table.RemoveColumns(dbo_DimCurrency,{"DimOrganization", "FactCurrencyRate", "FactInternetSales", "FactResellerSales"})
				in
				    #"Removed Duplicates key Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

