table DimDate
	lineageTag: 306afb33-9d68-491d-a065-0c3663a0bcc7

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 75c53dd5-1ac4-413a-8c2a-7862e25ba558
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column FullDateAlternateKey
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4320da55-c5db-4744-9762-39f6e4fda409
		summarizeBy: none
		sourceColumn: FullDateAlternateKey

		variation Variation
			isDefault
			relationship: d63e74c9-f1bd-416b-a6cf-d830dddfc8ce
			defaultHierarchy: LocalDateTable_a4054b8a-ec66-45e7-99c7-5fecb482eefc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DayNumberOfWeek
		dataType: int64
		formatString: 0
		lineageTag: cc9ebc22-9547-42fc-a6b8-3dc661446539
		summarizeBy: sum
		sourceColumn: DayNumberOfWeek

		annotation SummarizationSetBy = Automatic

	column EnglishDayNameOfWeek
		dataType: string
		lineageTag: a4bd100f-48fc-44cb-a9dc-d1bc63fb6410
		summarizeBy: none
		sourceColumn: EnglishDayNameOfWeek

		annotation SummarizationSetBy = Automatic

	column SpanishDayNameOfWeek
		dataType: string
		lineageTag: ec22e917-092e-477c-a875-aa88ca07cd15
		summarizeBy: none
		sourceColumn: SpanishDayNameOfWeek

		annotation SummarizationSetBy = Automatic

	column FrenchDayNameOfWeek
		dataType: string
		lineageTag: 8c69a963-1062-4087-8816-fe32372e95cc
		summarizeBy: none
		sourceColumn: FrenchDayNameOfWeek

		annotation SummarizationSetBy = Automatic

	column DayNumberOfMonth
		dataType: int64
		formatString: 0
		lineageTag: ac788bca-dc7a-46e0-9c58-5535cebd4d56
		summarizeBy: sum
		sourceColumn: DayNumberOfMonth

		annotation SummarizationSetBy = Automatic

	column DayNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: 2289a5df-056f-4818-b9f4-c9d31a25a3a0
		summarizeBy: sum
		sourceColumn: DayNumberOfYear

		annotation SummarizationSetBy = Automatic

	column WeekNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: 340839f5-c32c-432e-8052-a54659c1f889
		summarizeBy: sum
		sourceColumn: WeekNumberOfYear

		annotation SummarizationSetBy = Automatic

	column EnglishMonthName
		dataType: string
		lineageTag: a3611f1c-ab75-45df-8de1-30115dd62d6f
		summarizeBy: none
		sourceColumn: EnglishMonthName

		annotation SummarizationSetBy = Automatic

	column SpanishMonthName
		dataType: string
		lineageTag: d8e776da-fdaa-4b8a-9b4e-f88297a104ce
		summarizeBy: none
		sourceColumn: SpanishMonthName

		annotation SummarizationSetBy = Automatic

	column FrenchMonthName
		dataType: string
		lineageTag: 24469005-e1e2-4fd9-99fd-356c8be4ff75
		summarizeBy: none
		sourceColumn: FrenchMonthName

		annotation SummarizationSetBy = Automatic

	column MonthNumberOfYear
		dataType: int64
		formatString: 0
		lineageTag: c287eb35-3729-40dc-bbd2-ff972b16886f
		summarizeBy: sum
		sourceColumn: MonthNumberOfYear

		annotation SummarizationSetBy = Automatic

	column CalendarQuarter
		dataType: int64
		formatString: 0
		lineageTag: aa460c63-007a-4c79-beee-40be31a81e1e
		summarizeBy: sum
		sourceColumn: CalendarQuarter

		annotation SummarizationSetBy = Automatic

	column CalendarYear
		dataType: int64
		formatString: 0
		lineageTag: 40ec53c6-6d02-4bc1-a5a7-0de3488d6e5a
		summarizeBy: sum
		sourceColumn: CalendarYear

		annotation SummarizationSetBy = Automatic

	column CalendarSemester
		dataType: int64
		formatString: 0
		lineageTag: 38ccd59f-da8a-4d04-828f-aee9b0a4bd84
		summarizeBy: sum
		sourceColumn: CalendarSemester

		annotation SummarizationSetBy = Automatic

	column FiscalQuarter
		dataType: int64
		formatString: 0
		lineageTag: 74351b82-2a1f-4400-bcef-f2fde69c1877
		summarizeBy: sum
		sourceColumn: FiscalQuarter

		annotation SummarizationSetBy = Automatic

	column FiscalYear
		dataType: int64
		formatString: 0
		lineageTag: 152a18cf-9c0d-4479-8f98-de3e614b0237
		summarizeBy: sum
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

	column FiscalSemester
		dataType: int64
		formatString: 0
		lineageTag: ad1c3757-13b0-4d34-bd6e-f885ac9ccce3
		summarizeBy: sum
		sourceColumn: FiscalSemester

		annotation SummarizationSetBy = Automatic

	partition DimDate = m
		mode: import
		queryGroup: Time
		source =
				let
				    Source = Sql.Database(".", "AdventureWorksDW2022"),
				    dbo_DimDate = Source{[Schema="dbo",Item="DimDate"]}[Data],
				    #"Removed Duplicates key Columns" = Table.SelectColumns(dbo_DimDate,{"DateKey", "FullDateAlternateKey", "DayNumberOfWeek", "EnglishDayNameOfWeek", "SpanishDayNameOfWeek", "FrenchDayNameOfWeek", "DayNumberOfMonth", "DayNumberOfYear", "WeekNumberOfYear", "EnglishMonthName", "SpanishMonthName", "FrenchMonthName", "MonthNumberOfYear", "CalendarQuarter", "CalendarYear", "CalendarSemester", "FiscalQuarter", "FiscalYear", "FiscalSemester"})
				in
				    #"Removed Duplicates key Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

