table DimEmployee
	lineageTag: 160a4112-f97a-4677-baee-4512aed8d6fe

	column EmployeeKey
		dataType: int64
		formatString: 0
		lineageTag: 8eec8d26-7894-4730-a424-6abafbeb899a
		summarizeBy: none
		sourceColumn: EmployeeKey

		annotation SummarizationSetBy = Automatic

	column ParentEmployeeKey
		dataType: int64
		formatString: 0
		lineageTag: 34a56edb-e065-4c8c-bfe6-ee81711b9646
		summarizeBy: count
		sourceColumn: ParentEmployeeKey

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: bffee34d-915f-4a78-996f-bf21aed81110
		summarizeBy: count
		sourceColumn: SalesTerritoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: e6bda465-e199-4dc1-9261-b79981ca1def
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column HireDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 001b0228-28ce-4fa1-ab4b-5aac1ba41ad2
		summarizeBy: none
		sourceColumn: HireDate

		variation Variation
			isDefault
			relationship: 7604bd10-4837-4444-a9df-edb56035f778
			defaultHierarchy: LocalDateTable_8d8a7769-c6ae-4d71-aeb2-c6b0c99cb41b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column BirthDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8d49f8be-44e6-4cb9-a7d2-2bd9106a6523
		summarizeBy: none
		sourceColumn: BirthDate

		variation Variation
			isDefault
			relationship: e1a5a397-89c7-4968-b586-db2d9667d512
			defaultHierarchy: LocalDateTable_e41d7f98-18db-486b-9d23-603a74f31753.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column EmailAddress
		dataType: string
		lineageTag: ce3118a4-3e86-4d56-a034-59dfaaad383d
		summarizeBy: none
		sourceColumn: EmailAddress

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: string
		lineageTag: 967acd19-2a40-4ede-ab93-3fed46e4ffec
		summarizeBy: none
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	column MaritalStatus
		dataType: string
		lineageTag: ffe4bd9f-0199-446f-8890-003be20732fc
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 7de92884-2c05-4dec-8e2d-9faf64898829
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column PayFrequency
		dataType: int64
		formatString: 0
		lineageTag: 04f66d26-9623-4931-81bb-494253bf7970
		summarizeBy: sum
		sourceColumn: PayFrequency

		annotation SummarizationSetBy = Automatic

	column BaseRate
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: fed41a8c-8844-41d8-b392-a444957febf2
		summarizeBy: sum
		sourceColumn: BaseRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column VacationHours
		dataType: int64
		formatString: 0
		lineageTag: 7d3e17e8-6a3e-430f-8dfa-9338d72f9b96
		summarizeBy: sum
		sourceColumn: VacationHours

		annotation SummarizationSetBy = Automatic

	column SickLeaveHours
		dataType: int64
		formatString: 0
		lineageTag: d62c12d9-8708-4e81-b4e8-45df7ba62964
		summarizeBy: sum
		sourceColumn: SickLeaveHours

		annotation SummarizationSetBy = Automatic

	column SalesPersonFlag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0441b77d-a2f9-421c-9871-1d7102462f1a
		summarizeBy: none
		sourceColumn: SalesPersonFlag

		annotation SummarizationSetBy = Automatic

	column DepartmentName
		dataType: string
		lineageTag: 558e56b0-77d9-4b14-a21b-e93a74ee95d0
		summarizeBy: none
		sourceColumn: DepartmentName

		annotation SummarizationSetBy = Automatic

	column 'Full Name'
		dataType: string
		lineageTag: 3eb9841f-2a1d-4108-b3b4-13a20d9c0628
		summarizeBy: none
		sourceColumn: Full Name

		annotation SummarizationSetBy = Automatic

	partition DimEmployee = m
		mode: import
		queryGroup: 'Dim Sales Context'
		source =
				let
				    Source = Sql.Database(".", "AdventureWorksDW2022"),
				    dbo_DimEmployee = Source{[Schema="dbo",Item="DimEmployee"]}[Data],
				    #"Removed Duplicates key Columns" = Table.RemoveColumns(dbo_DimEmployee,{"DimEmployee(EmployeeKey)", "DimEmployee(ParentEmployeeKey)", "DimSalesTerritory", "FactResellerSales", "FactSalesQuota"}),
				    #"Removed Unnecessary Columns" = Table.SelectColumns(#"Removed Duplicates key Columns",{"EmployeeKey", "ParentEmployeeKey", "SalesTerritoryKey", "FirstName", "LastName", "MiddleName", "Title", "HireDate", "BirthDate", "EmailAddress", "Phone", "MaritalStatus", "Gender", "PayFrequency", "BaseRate", "VacationHours", "SickLeaveHours", "SalesPersonFlag", "DepartmentName"}),
				    #"Merge names Parts Columns" = Table.CombineColumns(#"Removed Unnecessary Columns",{"FirstName", "MiddleName", "LastName"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"Full Name"),
				    #"Reordered Columns" = Table.ReorderColumns(#"Merge names Parts Columns",{"EmployeeKey", "ParentEmployeeKey", "SalesTerritoryKey", "Full Name", "Title", "EmailAddress", "HireDate", "BirthDate", "Phone", "MaritalStatus", "Gender", "PayFrequency", "BaseRate", "VacationHours", "SickLeaveHours", "SalesPersonFlag", "DepartmentName"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

