table DimProduct
	lineageTag: 06235a50-e1bd-4695-bdc1-811451edb5d4

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 15693969-1fb3-407a-85d5-a040869c5cb1
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductAlternateKey
		dataType: string
		lineageTag: 3569e650-b060-445e-8c1c-9860f453eb80
		summarizeBy: none
		sourceColumn: ProductAlternateKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 264e592b-bb6a-4b22-afd8-22ffed5ecce0
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column EnglishProductName
		dataType: string
		lineageTag: 45da9bfb-2b20-4b3a-86cc-9dd4e182dd11
		summarizeBy: none
		sourceColumn: EnglishProductName

		annotation SummarizationSetBy = Automatic

	column StandardCost
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: c8511204-9da4-4b83-b928-4a8f00b85bb5
		summarizeBy: sum
		sourceColumn: StandardCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column ListPrice
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: dd98a2ab-6eef-449f-9348-bd329820a653
		summarizeBy: sum
		sourceColumn: ListPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Size
		dataType: string
		lineageTag: ca87a294-dcb1-4d35-8f8a-2d1592252223
		summarizeBy: none
		sourceColumn: Size

		annotation SummarizationSetBy = Automatic

	column SizeRange
		dataType: string
		lineageTag: 7d20fe23-abde-4626-9fd3-a845222930d1
		summarizeBy: none
		sourceColumn: SizeRange

		annotation SummarizationSetBy = Automatic

	column ProductLine
		dataType: string
		lineageTag: 4f941a46-e5fb-4da0-b4b7-7b9d5efd704c
		summarizeBy: none
		sourceColumn: ProductLine

		annotation SummarizationSetBy = Automatic

	column DealerPrice
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: db892448-d5a1-42fe-bd96-c9e51f750024
		summarizeBy: sum
		sourceColumn: DealerPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Class
		dataType: string
		lineageTag: 0b01e41c-f846-46d6-8482-211dadf3ad10
		summarizeBy: none
		sourceColumn: Class

		annotation SummarizationSetBy = Automatic

	column Style
		dataType: string
		lineageTag: b1c8e457-da6d-4717-878d-3eccbebb8163
		summarizeBy: none
		sourceColumn: Style

		annotation SummarizationSetBy = Automatic

	column ModelName
		dataType: string
		lineageTag: 12f2ff0a-dccc-4c73-9da8-15c2fb50ea90
		summarizeBy: none
		sourceColumn: ModelName

		annotation SummarizationSetBy = Automatic

	partition DimProduct = m
		mode: import
		queryGroup: 'Dim product'
		source = ```
				let
				    Source = Sql.Database(".", "AdventureWorksDW2022"),
				    dbo_DimProduct = Source{[Schema="dbo",Item="DimProduct"]}[Data],
				    #"Removed Duplicates key Columns" = Table.RemoveColumns(dbo_DimProduct,{"DimProductSubcategory", "FactInternetSales", "FactProductInventory", "FactResellerSales"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Duplicates key Columns", each true),
				    // Columns Like Descriptions or names in other languages 
				    #"Removed Unnecessary Columns" = Table.SelectColumns(#"Filtered Rows",{"ProductKey", "ProductAlternateKey", "ProductSubcategoryKey", "EnglishProductName", "StandardCost", "ListPrice", "Size", "SizeRange", "ProductLine", "DealerPrice", "Class", "Style", "ModelName"})
				in
				    #"Removed Unnecessary Columns"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

