table DimPromotion
	lineageTag: e841a614-9b2a-4fe3-93ab-04e489d434bb

	column PromotionKey
		dataType: int64
		formatString: 0
		lineageTag: 59eac39a-8c9d-4ad9-85bb-27bdb7925bc8
		summarizeBy: count
		sourceColumn: PromotionKey

		annotation SummarizationSetBy = Automatic

	column PromotionAlternateKey
		dataType: int64
		formatString: 0
		lineageTag: 0029ada5-162c-45d4-8a86-6db070c2154d
		summarizeBy: count
		sourceColumn: PromotionAlternateKey

		annotation SummarizationSetBy = Automatic

	column EnglishPromotionName
		dataType: string
		lineageTag: 1d1dc988-e275-4ea1-82b4-1454c16457f8
		summarizeBy: none
		sourceColumn: EnglishPromotionName

		annotation SummarizationSetBy = Automatic

	column DiscountPct
		dataType: double
		lineageTag: 96a01f7d-a4b3-45b0-8e00-0b7c0a4fb8af
		summarizeBy: sum
		sourceColumn: DiscountPct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EnglishPromotionType
		dataType: string
		lineageTag: e4f895bc-ffe5-43fd-a637-ddd6b1910054
		summarizeBy: none
		sourceColumn: EnglishPromotionType

		annotation SummarizationSetBy = Automatic

	column EnglishPromotionCategory
		dataType: string
		lineageTag: cabb84e8-1c98-420c-93d8-5eb54222e312
		summarizeBy: none
		sourceColumn: EnglishPromotionCategory

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 06afa444-ea64-41b9-8bad-a3836714cde4
		summarizeBy: none
		sourceColumn: StartDate

		variation Variation
			isDefault
			relationship: fc3a6443-0263-42a7-bc3b-cfd7de0806ae
			defaultHierarchy: LocalDateTable_62840b8e-30f8-4f43-855d-785b06df304e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column EndDate
		dataType: dateTime
		formatString: General Date
		lineageTag: dba2b616-9502-443b-b68f-4433bb99a71f
		summarizeBy: none
		sourceColumn: EndDate

		variation Variation
			isDefault
			relationship: 5c06e833-21d9-4ac3-88cb-61cd3f95b503
			defaultHierarchy: LocalDateTable_c6bbe650-dc15-4fde-ad3a-265b6039f4b3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column MinQty
		dataType: int64
		formatString: 0
		lineageTag: a0024f82-f8d3-4de8-8a76-c103ac0ac9d9
		summarizeBy: sum
		sourceColumn: MinQty

		annotation SummarizationSetBy = Automatic

	column MaxQty
		dataType: int64
		formatString: 0
		lineageTag: 4d86f8bb-a67f-4d19-891d-8f2d4bd01a21
		summarizeBy: sum
		sourceColumn: MaxQty

		annotation SummarizationSetBy = Automatic

	partition DimPromotion = m
		mode: import
		queryGroup: 'Dim Sales Context'
		source =
				let
				    Source = Sql.Database(".", "AdventureWorksDW2022"),
				    dbo_DimPromotion = Source{[Schema="dbo",Item="DimPromotion"]}[Data],
				    #"Removed Duplicates key Columns" = Table.RemoveColumns(dbo_DimPromotion,{"FactInternetSales", "FactResellerSales"}),
				    #"Removed Unnecessary Columns" = Table.SelectColumns(#"Removed Duplicates key Columns",{"PromotionKey", "PromotionAlternateKey", "EnglishPromotionName", "DiscountPct", "EnglishPromotionType", "EnglishPromotionCategory", "StartDate", "EndDate", "MinQty", "MaxQty"})
				in
				    #"Removed Unnecessary Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

