table DimProduct
	lineageTag: 06235a50-e1bd-4695-bdc1-811451edb5d4

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 15693969-1fb3-407a-85d5-a040869c5cb1
		summarizeBy: count
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductAlternateKey
		dataType: string
		lineageTag: 3569e650-b060-445e-8c1c-9860f453eb80
		summarizeBy: none
		sourceColumn: ProductAlternateKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 264e592b-bb6a-4b22-afd8-22ffed5ecce0
		summarizeBy: count
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column WeightUnitMeasureCode
		dataType: string
		lineageTag: 5608beb1-fb11-4db0-8088-04f52876a61d
		summarizeBy: none
		sourceColumn: WeightUnitMeasureCode

		annotation SummarizationSetBy = Automatic

	column SizeUnitMeasureCode
		dataType: string
		lineageTag: 221edd52-af6f-4f9f-b7ba-d922dcc94f17
		summarizeBy: none
		sourceColumn: SizeUnitMeasureCode

		annotation SummarizationSetBy = Automatic

	column EnglishProductName
		dataType: string
		lineageTag: 45da9bfb-2b20-4b3a-86cc-9dd4e182dd11
		summarizeBy: none
		sourceColumn: EnglishProductName

		annotation SummarizationSetBy = Automatic

	column SpanishProductName
		dataType: string
		lineageTag: b7b54398-c7c0-4eb3-9c03-13fa5cd9cdf4
		summarizeBy: none
		sourceColumn: SpanishProductName

		annotation SummarizationSetBy = Automatic

	column FrenchProductName
		dataType: string
		lineageTag: c2f06009-5fee-4fbb-94fb-c748a029045d
		summarizeBy: none
		sourceColumn: FrenchProductName

		annotation SummarizationSetBy = Automatic

	column StandardCost
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: c8511204-9da4-4b83-b928-4a8f00b85bb5
		summarizeBy: sum
		sourceColumn: StandardCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column FinishedGoodsFlag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f88922dc-b074-4371-ae45-64cf9685eb36
		summarizeBy: none
		sourceColumn: FinishedGoodsFlag

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: c48c5737-c3fa-4876-aaa9-758ab818a82c
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column SafetyStockLevel
		dataType: int64
		formatString: 0
		lineageTag: 1cf964e0-2be9-4269-a67c-1de148681f19
		summarizeBy: sum
		sourceColumn: SafetyStockLevel

		annotation SummarizationSetBy = Automatic

	column ReorderPoint
		dataType: int64
		formatString: 0
		lineageTag: 5bf0ffa6-093e-4021-9839-ee8712c2e7d7
		summarizeBy: sum
		sourceColumn: ReorderPoint

		annotation SummarizationSetBy = Automatic

	column ListPrice
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: dd98a2ab-6eef-449f-9348-bd329820a653
		summarizeBy: sum
		sourceColumn: ListPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Size
		dataType: string
		lineageTag: ca87a294-dcb1-4d35-8f8a-2d1592252223
		summarizeBy: none
		sourceColumn: Size

		annotation SummarizationSetBy = Automatic

	column SizeRange
		dataType: string
		lineageTag: 7d20fe23-abde-4626-9fd3-a845222930d1
		summarizeBy: none
		sourceColumn: SizeRange

		annotation SummarizationSetBy = Automatic

	column Weight
		dataType: double
		lineageTag: 74eb91b2-e601-4654-9d00-a4b33a4a46e2
		summarizeBy: sum
		sourceColumn: Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DaysToManufacture
		dataType: int64
		formatString: 0
		lineageTag: 1feee7bd-9c14-4cf6-b980-064dfdc7b82e
		summarizeBy: sum
		sourceColumn: DaysToManufacture

		annotation SummarizationSetBy = Automatic

	column ProductLine
		dataType: string
		lineageTag: 4f941a46-e5fb-4da0-b4b7-7b9d5efd704c
		summarizeBy: none
		sourceColumn: ProductLine

		annotation SummarizationSetBy = Automatic

	column DealerPrice
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: db892448-d5a1-42fe-bd96-c9e51f750024
		summarizeBy: sum
		sourceColumn: DealerPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Class
		dataType: string
		lineageTag: 0b01e41c-f846-46d6-8482-211dadf3ad10
		summarizeBy: none
		sourceColumn: Class

		annotation SummarizationSetBy = Automatic

	column Style
		dataType: string
		lineageTag: b1c8e457-da6d-4717-878d-3eccbebb8163
		summarizeBy: none
		sourceColumn: Style

		annotation SummarizationSetBy = Automatic

	column ModelName
		dataType: string
		lineageTag: 12f2ff0a-dccc-4c73-9da8-15c2fb50ea90
		summarizeBy: none
		sourceColumn: ModelName

		annotation SummarizationSetBy = Automatic

	column EnglishDescription
		dataType: string
		lineageTag: c3479a1a-b7d9-4f35-b42d-0658a9daf22b
		summarizeBy: none
		sourceColumn: EnglishDescription

		annotation SummarizationSetBy = Automatic

	column FrenchDescription
		dataType: string
		lineageTag: 921f9cb4-88f2-4b19-9f69-8cbb054b292f
		summarizeBy: none
		sourceColumn: FrenchDescription

		annotation SummarizationSetBy = Automatic

	column ChineseDescription
		dataType: string
		lineageTag: 13194169-8410-4b2a-acec-1b656b6b8dbe
		summarizeBy: none
		sourceColumn: ChineseDescription

		annotation SummarizationSetBy = Automatic

	column ArabicDescription
		dataType: string
		lineageTag: 02705f6d-8985-41da-9829-994d86cca20b
		summarizeBy: none
		sourceColumn: ArabicDescription

		annotation SummarizationSetBy = Automatic

	column HebrewDescription
		dataType: string
		lineageTag: af90a977-76f7-4172-8bb9-56efcf0a3af3
		summarizeBy: none
		sourceColumn: HebrewDescription

		annotation SummarizationSetBy = Automatic

	column ThaiDescription
		dataType: string
		lineageTag: 780189e8-db0f-4109-a829-95b83ade1538
		summarizeBy: none
		sourceColumn: ThaiDescription

		annotation SummarizationSetBy = Automatic

	column GermanDescription
		dataType: string
		lineageTag: c7674771-f251-4df4-99d0-37bca63290cf
		summarizeBy: none
		sourceColumn: GermanDescription

		annotation SummarizationSetBy = Automatic

	column JapaneseDescription
		dataType: string
		lineageTag: 0eccc041-c91a-47a1-a10c-bc03c3293450
		summarizeBy: none
		sourceColumn: JapaneseDescription

		annotation SummarizationSetBy = Automatic

	column TurkishDescription
		dataType: string
		lineageTag: 74d9d531-fe66-4675-99f0-934a5ca1c21d
		summarizeBy: none
		sourceColumn: TurkishDescription

		annotation SummarizationSetBy = Automatic

	column StartDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 2ac3cce2-5a01-4ce6-8001-f30e37745eb9
		summarizeBy: none
		sourceColumn: StartDate

		variation Variation
			isDefault
			relationship: 6d6c0f9d-ec24-49e9-83e0-dc07cebaaffe
			defaultHierarchy: LocalDateTable_fb99d0d0-86c3-4930-800b-7494e58f0f6d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column EndDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 9699631c-d0ba-4b00-8867-873430442a9a
		summarizeBy: none
		sourceColumn: EndDate

		variation Variation
			isDefault
			relationship: a8d0b109-b88d-4570-9e3b-911ef94ccd51
			defaultHierarchy: LocalDateTable_985b9f4e-3a81-469d-b588-29d26e859605.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 3cd4e0d6-f9b3-4800-a12a-a42ca6684823
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition DimProduct = m
		mode: import
		queryGroup: 'Dim product'
		source =
				let
				    Source = Sql.Database(".", "AdventureWorksDW2022"),
				    dbo_DimProduct = Source{[Schema="dbo",Item="DimProduct"]}[Data],
				    #"Removed Duplicates key Columns" = Table.RemoveColumns(dbo_DimProduct,{"DimProductSubcategory", "FactInternetSales", "FactProductInventory", "FactResellerSales"})
				in
				    #"Removed Duplicates key Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

