table DimProductSubcategory
	lineageTag: 54896d34-7f5b-4d84-88af-6f5d95762731

	column ProductSubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 188bf29c-336f-40a2-bf3e-6af64771cb4b
		summarizeBy: count
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryAlternateKey
		dataType: int64
		formatString: 0
		lineageTag: 12c41fc4-4c69-4375-9c9e-b69ca9a878ad
		summarizeBy: count
		sourceColumn: ProductSubcategoryAlternateKey

		annotation SummarizationSetBy = Automatic

	column EnglishProductSubcategoryName
		dataType: string
		lineageTag: 2a59e326-2237-4d96-8a5e-4a7ab8b401c2
		summarizeBy: none
		sourceColumn: EnglishProductSubcategoryName

		annotation SummarizationSetBy = Automatic

	column ProductCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: daa471ca-9acb-45a2-9cb2-6469598d4ae5
		summarizeBy: count
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	partition DimProductSubcategory = m
		mode: import
		queryGroup: 'Dim product'
		source = ```
				let
				    Source = Sql.Database(".", "AdventureWorksDW2022"),
				    dbo_DimProductSubcategory = Source{[Schema="dbo",Item="DimProductSubcategory"]}[Data],
				    #"Removed Duplicates key Columns" = Table.RemoveColumns(dbo_DimProductSubcategory,{"DimProduct", "DimProductCategory"}),
				    // Columns Like Descriptions or names in other languages 
				    #"Removed Unnecessary Columns" = Table.SelectColumns(#"Removed Duplicates key Columns",{"ProductSubcategoryKey", "ProductSubcategoryAlternateKey", "EnglishProductSubcategoryName", "ProductCategoryKey"})
				in
				    #"Removed Unnecessary Columns"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

