table FactSalesQuota
	lineageTag: 4c374958-43ae-46fd-b3ab-62cc2f285aba

	column EmployeeKey
		dataType: int64
		formatString: 0
		lineageTag: 7a342ed7-fee8-408b-9dd5-c07f2f27ce7f
		summarizeBy: count
		sourceColumn: EmployeeKey

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 18742613-18fb-4bc7-be13-0dfcf28d7403
		summarizeBy: count
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column SalesAmountQuota
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: d40f0268-8ca0-4394-aac3-5235791c44ce
		summarizeBy: sum
		sourceColumn: SalesAmountQuota

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition FactSalesQuota = m
		mode: import
		queryGroup: 'Fact Tables'
		source =
				let
				    Source = Sql.Database(".", "AdventureWorksDW2022"),
				    dbo_FactSalesQuota = Source{[Schema="dbo",Item="FactSalesQuota"]}[Data],
				    #"Removed Duplicates key Columns" = Table.RemoveColumns(dbo_FactSalesQuota,{"DimDate", "DimEmployee", "Date", "SalesQuotaKey", "CalendarYear", "CalendarQuarter"})
				in
				    #"Removed Duplicates key Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

